### ISSUE TITLE
[ECOSYSTEM CHALLENGE] Using Remix And MetaMask On Moonbeam

### ISSUE THREAD

**Issue by albertov19** [dcarpintero/hello-world-by-polkadot#2]
Hi dcarpintero,

Regarding your MetaMask submission, please ensure the amount allowed is the correct one (currently is 0.5)

Thanks

**Comment by dcarpintero** [comment]
Hi albertov19,

Indeed, the allowance was 0.5 instead of > 5 ERC20_HAK - I have added 25 Token to the address 0x12Cb274aAD8251C875c0bf6872b67d9983E53fDd 
(TX: 0x1f3276df876dec61d3328115fa9b6087263f350c3fcb7ed3667a1f3cde264b9)

Apologies for the inconvenience
![ERC_HAK_SpendingLimit_0x12Cb274aAD8251C875c0bf6872b67d9983E53fDd](https://user-images.githubusercontent.com/6709785/99122771-3f128a80-25ff-11eb-814a-61c0a92c8b09.png)
